baseURL = 'https://mengxi.space'
languageCode = 'zh-cn'
title = "Mengxi's Digital Garden"
theme = 'starter-theme'
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  defaultTheme = 'auto'
  homeInfoParams.Title = "Mengxi's Digital Garden"
  homeInfoParams.Content = "Tools, thoughts, and things that grow slowly."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/xiyuefox"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 20
  [[menu.main]]
    name = "HN Feed"
    url = "/hackernews"
    weight = 30
  [[menu.main]]
    name = "Bookmarks"
    url = "/bookmarks/"
    weight = 40
  [[menu.main]]
    name = "Search"
    url = "/search"
    weight = 50
  [[menu.main]]
    name = "Timeline"
    url = "/timeline"
    weight = 60

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    style = "dracula"

[taxonomies]
  category = "categories"
  tag = "tags"
